name: email 

on:  
  workflow_dispatch:
  schedule:
    - cron:  '30 4 * * 1-5'

jobs:
  email:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Prepare the environment
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0  
    # Step 2: Set Dynamic Date Environment Variables
    - name: Set current date as env variable
      run: echo "TODAY=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Echo current date
      run: echo ${{env.TODAY}}
    # Step 3
    - name: Send mail
      uses: dawidd6/action-send-mail@v3
      with:
        # Required mail server address:
        server_address: smtp.gmail.com
        # Required mail server port:
        server_port: 465
        # Optional (recommended): mail server username:
        username: ${{secrets.MAIL_USERNAME}}
        # Optional (recommended) mail server password:
        password: ${{secrets.MAIL_PASSWORD}}
        # Required mail subject:
        subject: Court Calendar Webscrape for {{env.TODAY}} at 8:00 am
        # Required recipients' addresses:
        to: nmcmillan@npr.org, bvanwoerkom@npr.org
        # Required sender full name (address can be skipped):
        from: Nick McMillan # <user@example.com>
        # Optional whether this connection use TLS (default is true if server_port is 465)
        secure: true
        # Optional plain body:
        body: Attached to this email is the csv of the court calendar captured at 8:00 am on {{env.TODAY}}.         
        # body: Build job of ${{github.repository}} completed successfully!
        # Optional HTML body read from file:
        # html_body: file://README.html
        # Optional carbon copy recipients:
        # cc: kyloren@example.com,leia@example.com
        # Optional blind carbon copy recipients:
        # bcc: r2d2@example.com,hansolo@example.com
        # Optional recipient of the email response:
        # reply_to: luke@example.com
        # Optional Message ID this message is replying to:
        # in_reply_to: <random-luke@example.com>
        # Optional unsigned/invalid certificates allowance:
        ignore_cert: true
        # Optional converting Markdown to HTML (set content_type to text/html too):
        convert_markdown: true
        # Optional attachments:
        attachments: ./data/days/${{env.TODAY}}-court_calendar.csv
        # Optional priority: 'high', 'normal' (default) or 'low'
        # priority: low      

