name: Scrape latest data

on:  
  workflow_dispatch:
  schedule:
    - cron:  '0 */2 * * 1-5'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Prepare the environment
    - name: Check out this repo
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
   
    # Step 2: Install requirements, so Python script can run
    - name: Install requirements
      run: python -m pip install pandas tqdm  requests beautifulsoup4
    # Step 3    
    - name: Run script to create main csv
      run: python ./scripts/court-calendar-scraper.py    
    # Step 5
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
